title: Yo en github
author: Omar Berriel Sánchez
email: oberriel@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Comparto con ustedes algo interesante enfocado en el dearrollo de software y de 
  la programación. Me interesa Python, Java y las soluciones con API y Api Rest y el backend
  "Estudio no para saber más sino para ignorar menos".
  Colaboro en proyectos de desarrollo de softaware y TI desde el siglo XX.
  
# social links
twitter_username: omarberriel # DO NOT include the @ character, or else the build will fail!
github_username:  omarBerry # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
